### ISSUE TITLE
worker函数中执行网络操作 collector不返回任何数据？

### ISSUE THREAD

**Issue by ipetu** [aploium/mpms#4]
![image](https://user-images.githubusercontent.com/5442932/70532309-bb038780-1b91-11ea-88e1-0c0bc41da5a8.png)
![image](https://user-images.githubusercontent.com/5442932/70532321-c060d200-1b91-11ea-8a2d-3f56bbeccc4c.png)
![image](https://user-images.githubusercontent.com/5442932/70532386-e4bcae80-1b91-11ea-9aae-4f5135cc5377.png)

**Comment by zjuchenyuan** [comment]
先检查你自己的网络情况，注意到requests会使用系统配置的代理，在不使用mpms时能否完成requests请求？

建议加上timeout参数控制requests超时

**Comment by ipetu** [comment]
很奇怪的一件事，我在主线程中发了一个网络请求，work中的网络请求就能执行。我主线程中不加这个requets请求，work中的网络就发不出去.
![image](https://user-images.githubusercontent.com/5442932/70533874-eb005a00-1b94-11ea-9449-83468d399f38.png)
![image](https://user-images.githubusercontent.com/5442932/70533924-ffdced80-1b94-11ea-99c3-c62fc090f5f5.png)

**Comment by ipetu** [comment]
切换到 legacy-v1 版本可用~

**Comment by ipetu** [comment]
自己依赖库的问题~不好意思~
